# Generated by Django 5.0.3 on 2024-04-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='total',
            field=models.CharField(default=100000, max_length=200),
            preserve_default=False,
        ),
    ]
